# From github.com/marketplace/actions/go-cross-build v1.0.2
# workflow name
name: crossbuild

# on events
on:
  release:
    types:
      - created

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code inside the workspace directory of the runner
      - name: Checkout the repository
        uses: actions/checkout@v4

      # step 2: generate build files and dump inside the workspace directory of the runner
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "linux/arm, linux/386, windows/386, darwin/amd64"
          package: "wipechromium"
          name: "wipechromium"
          compress: "true"
          dest: "distrib"

      # step 3: Copy build-artifacts in the GitHub release
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         args: "./dist/*.tar.gz"

